### PR TITLE
fix: hide internal details of `IntertialCalibrateFuture` and give it a lifetime for safety

### LINKED ISSUE #224: `InertialCalibrateFuture` should be opaque in its implementation.
## Problem Description
Since this is a future stored as an enum, users can access the internal fields of the enum and construct their own future for calibration, which is actually *unsafe* in this case, since it makes a mutable SDK call without a `SmartPort` instance. Bad news.

# Solution
We need to make the fields of this type private by newtyping it, similar to `ControllerScreenWriteFuture`.

### PR DESCRIPTION
**Pull request by Gavin-Niederman**
## Describe the changes this PR makes. Why should it be merged?
Hides the internal state machine, gives it the lifetime of the IMU, and prevents you from constructing it without a valid IMU. 
Closes #224 
## Additional Context
- These are breaking changes (semver: major).
- Needs testing (I have an IMU but I'm tired and will test tomorrow)

### CODE REVIEW

File: packages/vexide-devices/src/smart/imu.rs [hunk 1]
```diff
@@ -943,7 +954,10 @@ impl core::future::Future for InertialCalibrateFuture {
                     unsafe { vexDeviceImuReset(vexDeviceGetByIndex(u32::from(port - 1))) }
```
Comment (Tropix126) [inline packages/vexide-devices/src/smart/imu.rs:954]: now that `imu` is stored in the future, I think we can pass `imu.device_handle()` here rather than a call to `vexDeviceGetByIndex(u32::from(port - 1))`.

**Review by Tropix126 — CHANGES_REQUESTED** [review]
LGTM once hardware tested

**Comment by Gavin-Niederman** [comment]
Hardware tests pass!
