### PR TITLE
fix: implement into smartport seperately for every smart device

### LINKED ISSUE #170: SmartPorts can be instantiated in safe code
## Bug Description

Through the SmartDevice trait, SmartPorts can be instantiated without an `unsafe` block.

## Code to reproduce
```rs
#![no_main]
#![no_std]

use vexide::{devices::smart::SmartDeviceType, prelude::*};

#[derive(Clone, Copy)]
struct PortFactory(u8);

impl SmartDevice for PortFactory {
    fn port_number(&self) -> u8 {
        self.0
    }
    fn device_type(&self) -> SmartDeviceType {
        SmartDeviceType::GenericSerial
    }
}

#[vexide::main]
async fn main(_peripherals: Peripherals) {
    let cloner = PortFactory(1);
    let port_a: SmartPort = cloner.into();
    let port_b: SmartPort = cloner.into();
    dbg!((port_a, port_b));
}
```

## Expected vs. actual behavior

Repro output:
```
[main.rs:24] (port_a, port_b) = (
    SmartPort {
        number: 1,
    },
    SmartPort {
        number: 1,
    },
)
```

Instead, this should fail to compile because it is unsafe to have multiple instances of the same SmartPort.

## Additional information
- I have tested this issue on the latest development release.
- Priority this issue should have (low/med/high): high

### PR DESCRIPTION
**Pull request by Gavin-Niederman**
## Describe the changes this PR makes. Why should it be merged?
Fixes an issue where `SmartPort`s could be duplicated through a bad from implementation on any type implementing `SmartDevice`.
Closes #170 
## Additional Context
- These are breaking changes (semver: major).

### CODE REVIEW

File: packages/vexide-devices/src/smart/distance.rs [hunk 1]
```diff
@@ -82,6 +82,13 @@ impl SmartDevice for DistanceSensor {
         SmartDeviceType::Distance
     }
 }
+impl From<DistanceSensor> for SmartPort {
+    fn from(device: DistanceSensor) -> Self {
+        // SAFETY: We can do this, since we ensure that the old smart port was disposed of.
+        // This can effectively be thought as a move out of the device's private `port` field.
+        unsafe { Self::new(device.port_number()) }
```
Comment (doinkythederp) [inline packages/vexide-devices/src/smart/distance.rs:89]: I think this could simply be `device.port`.

**Review by doinkythederp — APPROVED** [review]
